val x = catch :Error {
    throw(:Error)
    print("unreachable")
}
print(x)              ;; --> Error
